--XO-X-----XOX--XXXOXOOXXXXOOXOXXOXXXXXXXXXXOOXXXOOOOX----XXXXX- O % Witting Sipke - Maas Rainier (Dutch Open 1)
--XXXX----XXOX-XOXXXXXXXXXXXXXOX-XXXXOOXXXXXOXOX---XXOO---OXOOO- O % van de Zande Josbe. - Witting Sipke (Dutch Open 1)
XXXXXXXX-XOXXXXX---OXXXX--OOXXOX---OOXOX--OOOOXX--OOOOXX--OOOOXO O % den Haan Frank - Witting Sipke (Dutch Open 1)
-XXX-O--O-XXOO--OXXXXXOXOXXXXXXX-OXXOXXXXXOXXXXXX-OOXX----XXXX-- O % Maas Rainier - van de Zande Josbe. (Dutch Open 1)
-OOOOO----OOOOX----OXXXO--OOXOXOXXXXOOXOXXXXXOOO-OOOOOO--XXXXXX- X % Maas Rainier - Witting Sipke (Dutch Open 1)
--OOOO---XOOOO-OOOXOOOOOOOOXXOOOOOOOXOXOOOOOXXOO--OXOO-O---X-O-- O % van de Zande Josbe. - Witting Sipke (Dutch Open 1)
-OOOO-----OOO---OXXOOO--OOXXOOOXOOXOXOOX-OOXXXOXXOOOXX-X-XXXXXX- O % de Graaf Jan - Witting Sipke (Dutch Open 1)
-OOOO-X---OXOXXX-OOOXXXX-OOXXXOX-OOXOOOXXXXXXOOX--XOOOO--XXX--X- O % de Graaf Jan - Shaman David (Dutch Open 1)
--XOOO--O-XXOOOOOXXOXOOXOXXOOOX-OXOXOXX-OXXXXXX-O-XXXX----OXXX-- O % den Haan Frank - Shaman David (Dutch Open 1)
--XXXX-----XOX-X-XXXXXXX--XOOOXO-XXOOXOO--OOOOOOXXXXXOOOOOOO-XOO O % Witting Sipke - Shaman David (Dutch Open 1)
-XXX-O--X-XXOO--XXOOOXOOXXXXXXXXOXXXOXX--OXOXXXX--OXXXX--OOOOO-- O % de Graaf Jan - Shaman David (Dutch Open 1)
--OOOOO-OXXXXO---XXXOXXXXXOXXOXXXXOOXXO-XXXOOXOO--XXXO----XXOX-- O % Batha Matej - Rybarik Jan (Championnat TchËque)
--OOOOO-OXOOOO--OOOOXOOXOOOOOOXXOOOXXX-X-XOXX-OX-XXXX---OOOOO--- O % Stastna Jan - Rybarik Ivo (Championnat TchËque)
-XXXXX----XOOOO-OOXXXOOX-OOXXXOX-OXOOXOX-XXXOOOX--XXXXO--XXXXX-- O % Koblic Miroslav - Batha Matej (Championnat TchËque)
-OOOOOO-X-OOOO-X-OOOOOXXOOOXOXXX-XOOXXXXXXXXXXO---XOOO-O-X-OO--- O % Tesinsky Jakub - Kvapil Martin (Championnat TchËque)
--X--X--O-XXXX--OXXXXXOOXXXXXXOOOXXOOOXOOXXXOOOOO-XXXO--O-X-OOO- O % Kalfinov Zdravko - Krejcik Roman (Championnat TchËque)
--X-OOO-X-XOOO--XXOOOXXXXXXOXXXX-XOXXXXXOOXXXOXXO-XXXX----OXXO-- O % Kalfinov Zdravko - Stastna Jan (Championnat TchËque)
--OOOO-----XXXXO--XXXXXO--XXOOXO--XXOOXOOXXXXOXOXXXOOOOO--OOOOOO O % Tesinsky Jakub - Kalfinov Zdravko (Championnat TchËque)
----OXX----XXXXX--XXXOOXO-XXOXOXOOXOXXXXOOOXOXXXOOXXXXX-O-OOOO-- O % Kalfinov Zdravko - Voracek Miroslav (Championnat TchËque)
-OOOO-X---OXOX---OOOXOOOXOOOOXOOXXOOOOXO-XXOXXXXO-XXOO----XXXXX- O % Vit Jiri - Stastna Jan (Championnat TchËque)
XOOOOOO-X-OXXO--XOXOXXXXXOOXXXXXXOOXOXOXXXOOOOXXX-OO---X--O----- O % Krejcik Roman - Jelinek David (Championnat TchËque)
XXXOOX--OXXOOO--OOXXOOO-XOOXXXX-XOOOOX--XXOOOX--X-OOOO---OOOOOO- O % Sic Vojtech - Kalfinov Zdravko (Championnat TchËque)
X--X----XXXX----XXXX----XXXXXOO-XXXXXXOOXXXXXXXXXXXXXXXXXXXXXXXX O % Voracek Miroslav - Kvapil Martin (Championnat TchËque)
--X-O-----XOOO----OXOOOOXXXXXOOOXOOXOOXOXXOOXOXOX-OOOXXO--OOOOXO O % Hrabal Vojtech - Sic Vojtech (Championnat TchËque)
-OOOOOOO-OOOOOOO-XOOOOOO--XOOOOO--XXOOOO--XXXOOO--X-OOOO---OOOOO X % Koblic Miroslav - Sic Vojtech (Championnat TchËque)
-XXXXX----XOXX--OOOXXXXXOXXOOOX-OXOOOXX-OOXOXXXXO-XXXX---O-XXXX- O % Sic Vojtech - Tesinsky Jakub (Championnat TchËque)
-OOOOO---OOOOO--OOOXXOOOXOOOXOOOXOXOOOXOOXXXOXOO--X-XO-O---XXX-- O % Stastna Jan - Kalfinov Zdravko (Championnat TchËque)
-OOOOOO---OXXO--OOOOOX-XOOOOOXX-OOOXXOXXOOOXOOOO--XOOO----OOOOO- O % Stastna Jan - Tesinsky Jakub (Championnat TchËque)
-OOOOO----OXXXXO--OXOXXO--OOXXXO-OOXOOXOOOXOOOOO-XXOOOOO--OXXO-- O % Vit Jiri - Krejcik Roman (Championnat TchËque)
OOOOXXX-OXOOOXX-OOXOXOXXOXXOOXX-OXOOXX--OOOXX---OOXO----OOOOO--- X % Vit Jiri - Voracek Miroslav (Championnat TchËque)
--OOOO----XXXXX--XXXOXOOX-XXXOOOOXOOOOOOOOXOXOOO--OXXX---OOOOOO- O % Stastna Jan - Voracek Miroslav (Championnat TchËque)
--XOOX---XXOOO-XOOXOOOXX-OOXOXOXXOOOXOOXXOOOOXOXX-OOOOX-----OO-- O % Stastna Jan - Kalfinov Zdravko (Championnat TchËque)
--O-X---O-OXXO-OOOXOXOOOOXOXXXXOOXXXXXOOOXXOOXXO-XXOOO----XOOO-- O % Voracek Miroslav - Stastna Jan (Championnat TchËque)
-O-X-O--X-OXOOO-XXXXXXXXXXXOOXOOXOXOXOO-XXOXOXOOXOOOOO----O-XX-- O % Voracek Miroslav - Tesinsky Jakub (Championnat TchËque)
-OOOO-X---OXXX-OO-XXXXOO-OXXOOXO-XOOOXOOXXXOXOOO--OXOO-O--OOOOO- O % Stastna Jan - Voracek Miroslav (Championnat TchËque)
--XXXX--X-OXXX---XXOXXOOOOXXXXOOOOOXOXOOOXXOXXOO--XXXX-O--XXXX-- O % Jelinek David - Voracek Miroslav (Championnat TchËque)
---X------OXX--O-OOOXXOOOOOOOXX-OOOOOXXXOOOOOOXXOOOOOO-XOOOOOOO- O % Kvapil Martin - Voracek Miroslav (Championnat TchËque)
-XXXXXX-O-XXOO--OOXOXOXXOXOOOOX-OXOOXXX-OOXXXXXXO-XOX----XXXX--- O % Hvezdova Jitka - Tesinsky Jakub (Championnat TchËque)
-OOOOX---OOOXO-OOOOXX-O-OOXOOOOO-OXOOOOOXXOOOOOOX-OOOO----OOOO-- O % Hrabal Vojtech - Voracek Zdenek (Championnat TchËque)
--X-----OXXX---XOXXXXXXXOXOXOXOXOOXOOOXXOXOOOXXXOOOOXO--OOOOO--- O % Koblic Miroslav - Rybarik Ivo (Championnat TchËque)
-O------X-OO---XXX-OOOXXXOXOXXOXXOOXXXOXXOXXOOXXXXOXXX-XXXXXXX-- O % Hvezdova Jitka - Jelinek David (Championnat TchËque)
X-OXX---XXOX----XXXXOO--XXOXOOOOXXOXXOO-XXOXOO--XXOOOOO-XXXXXXX- O % Hrabal Vojtech - Rybarik Jan (Championnat TchËque)
-XXXXXXXOXOOOO--OXXOOOO-OXOXOO--OXOOOO--XXOOOO--XXOOO---XXXXXX-- O % Sic Vojtech - Batha Matej (Championnat TchËque)
-XXXXX--OXXXXX--OOXOOXXXOXOXXOO--XOXXOO-XXXOOXOO-XXXXX---OOO-X-- O % Jelinek David - Rybarik Ivo (Championnat TchËque)
-OOOOOO-X-XXXXX-XXXOOX--XXXXOXXXXOXXOXXXXOOXOX--X-XXXX----XXXX-- O % Batha Matej - Tesinsky Jakub (Championnat TchËque)
----------XX----OXXXXXX-OXXOOXXOOXOOOOXOOXOOOOXOOOOOOOOOOOOOOOOO X % Rybarik Jan - Voracek Miroslav (Championnat TchËque)
XXXXXX---XOOOO-OXOXXXXOO-OOXOXOOOOXOXOX--XXOXXXXX-OOOO-----OOO-- O % Rybarik Jan - Koblic Miroslav (Championnat TchËque)
-OOOOO----OOOX-OXXXXXOOOOOXOOOXOOOOXOOXOXOXOXXOO--OXXX-O--O-X--- O % Voracek Zdenek - Rybarik Jan (Championnat TchËque)
-XX-OO----XOOO-OOOOXXOO--OOXXOXX-OXOOOO-OXOOOOOOXXOXOO--OOOOOO-- O % Rybarik Jan - Hvezdova Jitka (Championnat TchËque)
--XXXX----XXXX-XXXXXOXXXXXXOXXXXXXXXXXOXXXXOOOOX--X-OOXX--X---OX O % Rybarik Jan - Hlavac Juraj (Championnat TchËque)
----OOO-O--XXOO-OOXXOOXX-XXOOXXXXOXOOXXXXXOOXXXXX-XXXX-X--XXXX-- O % Tesinsky Jakub - Krejcik Roman (Championnat TchËque)
XXXXXXXX-XOXXOXX-OXXXXXXOOOXXXXX-OOOXXXXX-OOXXOX---OX-XX-------X O % Krejcik Roman - Voracek Zdenek (Championnat TchËque)
---OXO----OXXX-OXXXXXOO-XXXXOOXXXOOOOOOXXXOXOOXXX-XOOO-X--OOOO-- O % Batha Matej - Kvapil Martin (Championnat TchËque)
--XOO---O-XOOO--OOXXXOOOOOXOXXX-OOXXOXXXOOXOOOXX-XOOOO-X-XXX-O-- O % Krejcik Roman - Hrabal Vojtech (Championnat TchËque)
-OOOOOOO--OOXXXOXXXOXOXO-XXXOXOO--XOOOXO--XOOXXX--XOOX----XXXXX- O % Kvapil Martin - Vit Jiri (Championnat TchËque)
X-XX-O--OXOOOO--OOXXOOOOOOXXXOOO-OXXXXOOXXOOXXXO--XXXX----XXXX-- O % Kvapil Martin - Hrabal Vojtech (Championnat TchËque)
--XXXXOO--XXXOOX--XOOOOX--XXXOOX--XOXXOO--XOOXOO--XOXOOO-XXXXXOO X % Koblic Miroslav - Krejcik Roman (Championnat TchËque)
-O-XXXX-X-OXXXX-XXOOXXOOXXOOXXO-XXXXXOOXXXXXOOO-X-OOXX----O-XX-- O % Voracek Miroslav - Hvezdova Jitka (Championnat TchËque)
-XXX-O----XXOO--XOOXOOXXXOOOXOX-XOOOOXXOXOOXXXX--OXXXX---XXXXXX- O % Sic Vojtech - Hvezdova Jitka (Championnat TchËque)
--OOOOO--OOXOO--XOOOXXXXXOXOXXXXXXXOXXXXXXXOXOO-X-XXX-----XXXX-- O % Voracek Miroslav - Krejcik Roman (Championnat TchËque)
-XXXX-O---XXOX---XXOOOXOOXXXOXXOOOXXOOXOO-OXXXOO--OOXX-O--XXXXO- O % Voracek Miroslav - Kvapil Martin (Championnat TchËque)
--XXXX----OXXX----OOXOOO-XOOOOOO--OOOOXOOOOXXOXO--OOXXOOXXXXXXXO O % Rybarik Ivo - Rybarik Jan (Championnat TchËque)
---OOOO---OOXOO-X-OXXXO--XXOOOOOOXOOOOOOOOOOOOOOOOOOOO----OOOOO- O % Hvezdova Jitka - Koblic Miroslav (Championnat TchËque)
--XXXX----XXXX-XXXXXXXX--XOXXXOO-XXOXOOOXXXXOXOOX-XXOO-O-XXXXX-- O % Hrabal Vojtech - Hvezdova Jitka (Championnat TchËque)
--XXXXX---XXXO-OOOXXOOOO--XXXXOO--OOXXOO--XXOXXO--XXXXXX-XXXXXOX O % Rybarik Ivo - Vit Jiri (Championnat TchËque)
-----X----XO-X--XXXOOXX-OXXOXXXXXXXXOXXOXXXOXXOOXXXXXXOOXOXXXX-- O % Kalfinov Zdravko - Vit Jiri (Championnat TchËque)
----O--O---OOOOO---XXXOOO-XXXXOOOOXOXXOOOOOXOXOOOOXXXXXOOOOOOO-- O % Hlavac Juraj - Vit Jiri (Championnat TchËque)
----XXXX----XXXX---XXXXXOOOXXXXX-OXXXXXX-XXXXXXXX-XXXXXX-XXXXXXX O % Rybarik Ivo - Hlavac Juraj (Championnat TchËque)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-OOOOOOX----O--O-------- O % Hubbard Geoff - Jassigui Moctar (Tournoi de Noel)
---OOOOX-OOOOOXXXXXXXXOX-XOXXOOX--OOXXOX--OOXOOX--OOOOOX---OOOO- O % Hubbard Geoff - Barot Jacques (Tournoi de Noel)
----OOOX----OOX-OOOOOXOOOOOOXOOOOOOXOOOOOOXXOOOOO-OOOO-O--OOOO-- O % Abe Hiroyuki - Barot Jacques (Tournoi de Noel)
X-O-XXX--XOXOX-XXOXXOOXXXXXXOXOXXXXOOOXXXXXXOXX---OOOO-----OOO-- O % Kashiwabara Takuji - Hubbard Geoff (Tournoi de Noel)
--XXXXO----XXOO---XOOXOOXXXOXXXXXXOXXO-XXOXXXOX--XXXXX--XXXXXXX- O % Nicolet Stephane - Caspard Emmanuel (Tournoi de Noel)
XXXXOO---OOOOOOOXOOXXXXXXOOXOOX-XOXOOOOOXXOOOOOOX-OOO--O-------- O % Caspard Emmanuel - Hubbard Geoff (Tournoi de Noel)
--O-O---OXOOO---OXXOOOO-OXOXOOOOOXOOXOOOOOOXOXO-OOOOXXX-O-OOOX-- O % Caspard Emmanuel - Scheidecker Denis (Tournoi de Noel)
---XX----OXXXO-X-OXXOOXX-OXOXXOXOXXOOOOXXXXXXOOX--XXOOO--XXXXXX- O % Nicolet Stephane - Kashiwabara Takuji (Tournoi de Noel)
-------O-O-X-XOOXXOXXXOOXXXOOOOO-XXXOOOO-XXOXXOOX-XXOOOO--XOOOOO X % Barot Jacques - Nicolet Stephane (Tournoi de Noel)
-------------X-XOX-XXXXXOXXXOXOXOXXOXXXOOXOOXXOOOOOOOOOOOXXXXXXX O % Seknadje Jose - Kashiwabara Takuji (Tournoi de Noel)
----XX-----XXX--OXXXXXXXOXXOXXXXOXOOXXXXOOOOOX--OOOOOXX-OOOOOOO- O % Jassigui Moctar - Scheidecker Denis (Tournoi de Noel)
-OOOOOO--XXXOOX---XXXXXX--XXXXXX--XXOOXX--OOXOXXXXXXXX--OOXXXXX- O % Diassy Paheraba - Seknadje Jose (Tournoi de Noel)
--OOOXO-OXOO-X--OOXXOX--OOOOOXOOOOOOXOOOOOOOOXOO--XXXXXO--XXX--- O % Auzende Frederic - Nicolet Stephane (Tournoi de Noel)
--XXX-O---XXXO--OOOXOOXOOOXOXXXO-OOXOXXO-OOOXXXO--OXO-OO-OOOOO-O O % Auzende Frederic - Hubbard Geoff (Tournoi de Noel)
--OOOOO---OOOOO-OOOXXOOO-XXXOOXO--OXOXOO--OOOOXO--OXOXXO--OOOOXO O % Nicolet Stephane - Abe Hiroyuki (Tournoi de Noel)
---O-O----OOOOXX--OOOXXX-OOOXXOXXOXXOXOXXXOOOOOXX-OOOOO--OOOOO-O O % Auzende Frederic - Seknadje Jose (Tournoi de Noel)
------O--XOOO-OX-XXOOOXX--OXOXOX-OOXXXXXX--XXXOXXXOOXXOXXXXXXXXX O % Caspard Emmanuel - Diassy Paheraba (Tournoi de Noel)
--XXXX----XXXX---OXXOOX-OOXXOXXXXXXOXXXXXXOOOOXX--OOOO-X-OOOOOO- O % Scheidecker Denis - Auzende Frederic (Tournoi de Noel)
--O-XX----OOXXX-XXOOOXXOXXOOOOXOXXXXOOXOXXXXXOOO--XXXX-O---XXXX- O % Seknadje Jose - Caspard Emmanuel (Tournoi de Noel)
---O----O--OOX-OOOOOXXOOOOOOXXXOOOXOXXOOOOOOXOOOO-XXXO-O--XXXXX- O % Abe Hiroyuki - Auzende Frederic (Tournoi de Noel)
O--XX---O-XXXX--OXXXXX--OOXXXX-XOOOOOXX-OOXOOXXOOXXXXXX--XXXXXX- X % Jassigui Moctar - Seknadje Jose (Tournoi de Noel)
-XXXXXX-X-XXOOO-XXXOXOOOXXOXOOOXXOXOOOXXOXXXXXXX-XOXX---X------- O % Yu Leong Wong - Ng Ka Fu (Championnat de Hong-Kong)
--O-----X-OOOO--XXOXOOOXOXXXXOXXOXXXOXXXOXXOXOX-OXOOOX--XXXXXX-- O % Wu Hujai - Ng Ka Fu (Championnat de Hong-Kong)
---O----X-OOO--XXOOOOOXXXXXXXXOXXXXXXXOXXXXXXOXX--XXOOO--XXXXXX- O % Wu Hujai - Mak Thomas (Championnat de Hong-Kong)
--XOO-----XOOO--XXOXXXX-OOXXXXX-OOXXOXX-OOXOOXXXOOOOXX--XXXXXXX- O % Wong Chi Yin - Tsoi Chun Yip (Championnat de Hong-Kong)
XXXXXXXX-XXXXXXX-OXXXXXX-OOXOOXX-OOOXOXX-O-OXXOX----XOOO-----XOO O % Wong Chi Yin - Leung Kai Wan (Championnat de Hong-Kong)
-OOOOO----XXXXXO-OOXXXXXOOOOXOXXOOOOOXOXOXXXOOOX--OOOO-X---OO--- O % Tsoi Chun Yip - Wu Hujai (Championnat de Hong-Kong)
-OOOOO--X-OOOOX-XXXOOXXOXOOXXOO-XOOXXOO-XXXXXO--XXXXOO----XXOO-- O % Tsoi Chun Yip - Ng Ka Fu (Championnat de Hong-Kong)
-----X---OX-XX--OOOXXXOOOOXOXXOOOXOXOXOOOOXXXOOOO-XOOXOO--XXXXX- O % Leung Kai Wan - Mak Thomas (Championnat de Hong-Kong)
--XXXXX---XXOX-OOXXOXOOO-XXXXOXOXXOXOOOOXXXOXOOO--XXOO----X-OOO- O % Leung Kai Wan - Yu Leong Wong (Championnat de Hong-Kong)
-XXXXX----XOXX--XXXXXXXOXXXOOXXOOOXXXOXOOOOXOXOO---OOO-O--OOOX-- O % Yu Leong Wong - Tsoi Chun Yip (Championnat de Hong-Kong)
--XXX--O-OOXXXOX-OOXOOOXXXXOXOOXXXXXOOOXXXXXXXXX--OXXX-X--X----X O % Wong Chi Yin - Ng Ka Fu (Championnat de Hong-Kong)
-XXXXX--O-XOXX--OOOXOXXXOOOOXOX-OOXOOOOO-OXXOOOO--XXOO-O---X---- X
--OXXX--XOXXXX-XXOOXXXXXXXOOXXXXXOXXXXXXOOOXOOXX---X---X---X---- X
----XX---XXXXXO-OOOXOOXXOOOOOXXXOOOOXX-XOOOOXX--O-OXOX---OOOO--- X
-XXX------OOXX-X-OOOOOXXOOOXOOOX-OXXXOOXOOOXOO-XXOOOO------XXXX- X
-------------XXXOOOOXXXXOOXXXXOXOXOOOOOOOOXXOOOOO-OXXOO---OOOOO- X
-OX-O-----OOO--OXXXOOOO-XXXXOXXXXXOOOXXXXXXXXOXX---XOO-X---OOOO- X
-XXXXXO-O-XXXOO-OOXXOXO-OXXOXO--OXOXXO--OXXXOO--OXOOOO----OO-X-- X
-XO-X---X-OOXO--XXOXOOXXXXOOXOXXX-OXOXOX--OXXXXX--XXXX-X-XXX-O-- X
-XXXXX----OXOX---OXOXOXXOXOOOOO-OOOOOOOOO-OOXXXO--OXXX-----XXXX- X
---OXX--X-OOXX-OXOOOXXO-XOOOXOXXOOOOXOXXOOXOXOXX--XXXX-X----X--- X
--XXXX----XXXX---OOXXOOOOOXOXXOO-OXOXOOOXXOOOXOO--XOOOX----OOO-- X
--XXXXXX---XOOOO--XXXXOO---XXXOO--XXXOOO-O-XXXOO--OXXXXO--OOOOOO X
--XXX-----XXXX-XXXXXXXXX-XXXXXXXXXXXXXOXOX-XXOOO---XOO----XXXXX- X
--O-XX----XXXX-OXXXXXXOO-XXOXOXO-XXXOXXOXXXXOOXO--OOXO----OOOO-- X
-OOOOOO-X-OXOO--XXOOOOX-XXOXOXX-XXXXXXX-XXOOO-O-X-OOO-----OOOO-- X
--O-----O-OX-X--OOOOXXXXOXOXOXOXOOXXOOOXOXOXXOOX-XXXOOO--X-XO--- X
OOOOO-XXOXXOOOOXOOXXOXOXOOOXOXOX--OOXXOX-O-OOOXX----OX-X-------- X
OOOOO---XOOOOO--XXOXXO--XOOOXX--XXOOXX--XXXOXXX--XXXOO---OOOOO-- X
-O-XXXX---OXXX---OOOOOOO-OOOOXO-OOOOOOOOOOOXXXXX--XXOX----XXXX-- X
O-OOOO--OXXXXX--OXXOX---OOOXXX--OOOXXX-O-OOXXXX-O-XXOO-X-OOOOO-- X
OOOOOOO-OOOXOXX-OOOXOX--OOOOOX--OOOOOX--OOOOO---OOXO----OOOOO--- X
-X-OOO---XXOOO--OXXOOOOOOXXXXO--OXXOOOO-OXOXX---O-XOXX---XXXXXX- X
--XXXXX-X-XXXO--XXXOXXO--XOOOOOOXOXOOXOOOXXOOOOO--OOOO----O--O-- X
--OOOOO---OXXXX--OOOOXXOOOXOOXOOOOOXOOOO-OXXOOOO--XXOO-O--X----- X
--O--O--X-OOOO--XXOOOOOOXOXOXOO-XXOXOOX-XXXXOXX-XXOOOO----OOOO-- X
-OOOO-X-X-OOOX--XXXOXO--XOXXOOO-XXXXXXOXXXOOOX-OX-OOXX----O-OX-- X
OOOOO---XOOXOO--XOOOOXX-XXXOOX--OXXXOO--XOXXO-O--XOOOO--X-OOOX-- X
-OOOOO---OOXX---OOOXX---OOXOX-O-OXOOOXOOXXXXOOOOXXXOXO----XXOO-- X
O-OOOOO--OXXXO--XXOOXXXX-XOOOX--XXXXXXX-OOOOOOO---OOOO----OOOO-- X
-OOOOO--X-OXXOO-XXOOOOOOXXXXOXXXXXOOOOOXXXOOOO--X-OO------O-O--- X
-OOOOO--O-OXXXO-OOXOX-OOOXOXX---OXXOXX--OXXXOX--OXOOOO----OOOOO- X
--OXOO--X-XXOO--XXXXXOO--OOOXXOOOXOOOXX-OOOOOOXXO-OOOO-----OOO-- X
-XXXX-----XXXO--XXXXOXO-XXXXXXX-XXOOOXO-XXXXXOO---OXX-OO-XXXXX-- X
-XXXXX----XXX---OOOOOOO-OOOOXOO-OXOXOXOOOXXOOXX-OXXXXX----OOO--- X
-------------O--XOOOOOOXXXOOOOOXXXXOOXOX-XOXXOOX-OXXXOOXO-OOOOOX X
---O-X--X-XOOO-X-XXXOOXXOOXXXXOXOOOOOOX-OOOOOXOO--OOXO-----OOOO- X
--XXXXOX--XXXOOX-OXXXXOXOOXXXOOX-XXXOOXXX-XXOXOX--OO---X--O----X X
---XXX--O-XXOX--OOXOOXOOOXXXXXOOOOXOXXXO-OXOOOOO--OOOX-O---O-X-- X
--O-----X-O-XO--XXOXOOO-XXOOXOOXXXOXOOOOXXOXOOOXX-OXOO---OOOOO-- X
--OOOO----OOOO-O--OOXOOO-OOXOOOOXXOOOOXO-XXOXXOO--XOOO-O-XXX-O-- X
--OOOX---OOOX--X-OOXOOOXOOXXXOOX-XXXOXXXXXOOOOX---OOOO-----OOOO- X
--OO----X-OOO---XXXXOOO-XXXXXXXXXXXXOOX-XXXXOXO--X-OXX--X-OOOOOO X
--XXXX----XXXX--O-XXOXOOOXXXOOOOOOXXXXOOOOXXOOOOO-X-OO----X-OO-- X
--XXXX--O-XOXX--OXOOXOOOOOOXXXOOOXOXXOOOOOXOOXO---OOX-----O-XO-- X
-OOOO-----OXXO---OOOOXXX-OXOOXXXOOOOXXXXXXXXXXXX--XXXO----XXXX-- X
XXXXXXX-OOXOXX-XOOXXOXXXOOOXXOXXX-OOOOOX-OOOXXXX--OX------------ X
-XXXXX--X-XXOOOXXOOXOOOXXOOXOOOXXOOXOOXXX--XOO-X--XXXO-----X---- X
--OOOO----OXOO--XXOOOOXX-XOOXOXXXOOOXXOXOXOOXXXX--XOXX-X--OX---- X
-OOOOO----OOOO--XXOXOXX-XOXXOXX-OOXXOXX-XOOOOXXXXOO-XX--OO-X---- X
--OO------OOOO--XXOXOOO-XXXXOXOXXXXXOXXXXXOXOXXXXOOOOX-X--OX---- X
--XXX------XXX-X--XOXXXX--OXXXXXOOOOXXXXOXOXXOO-O-OOOX-O-OOOOOO- X
---XXX-----XXX-OXXXXXXOOOOOOOOOO-OXXXOOOO-XOOOOO--OOOOX---OOXX-- X
OXO-----OOOOO---XOOXXOX-XXOOOXO-XOOOOOOOXXOXOOO-XXXOOO----OOO--- X
--XO----X-XOO--OXXXOXOOOXXXXOXX-XXXXOOXXXXXOOOXX---OOO-X--OOOO-- X
OO-OXX--OXOXOXX-OXXXXOXXOXXXXOOOOXXXXOOOOXXXXXOOO-X------------- X
---OOOOX--OOOOX--XOXOXXXXOXXOXXXOOOOXXXX--OXOXX---OOOX---XOO-X-- X
--OOOOO---OOOXX-O-XOOXX-O-OOXXO-OXXXXOOOOOXOOOOX--XXXX-----XXXX- X
----X-----OXXX-X--OOXOXXXXOXOXXXXOOOXOOXXXOOOXXXX-OOOOXX-OO--O-- X
--O-----O-OOO----OOOOOOOXOOOOOOOXXOXOOXOXOXXXXX-X-XXXX-X-XXXXX-- X
--XXXX-X--XOXOX-OOOOOOOO-OOXXOOX-OOXXOXXOOOXOOXX--XXXO-----X-O-- X
-OOOO-----XOOO-XOXOXXOXXOOXXXXXXOOOOXXXXOOOOOOXX--XOOO------O--- X
-OO-XX----OXXX--OOXOO-OX-OXOOOXX-XOXOXOX-OXOXOOX--XXOX-X--XXXXX- X
----------OXXX--O-OOXXOOOOOXOXOOOOOXXXXO-OOOOXXOXXOOOXX--XXXXX-- X
--X-------XO-O---XOOOOO-XOXOXOO-OXXXOOOOXOOOXOOO-OXXOXO--XXXXXXO X
-XXXXXXXO-XXXXXXOOOOOOXXOOOOOOOX-XOOXO--XXOOOO----OOO----OO----- X
-----O-----OOO--OOOOOOOOOXOXOOOOOOOXXOOOOOOOOXXX--OXOO---OOOOOO- X
O-OOOO--OOOOOO--OXOXOOO-OXOOXOXXOOOOOOXX--OOOOXX--OOOO----O--O-- X
---XOO-----XXOOO--XXXOOO--XXOOOO-XXXOOXO-XXOOOOO--OOOOOO-XXXXX-O X
--OOOX--X--OOOXOX-XXOXOOX-XOXOXOXXXXOXXOXXXXOXX---XXXX-X--X--X-- X
-------------X-O-XXXXXO-OXXOOOOXOXOXOXOXOOOOXOXXO-OOOXOX-OOOOOOO X
--XXXXX---XXOX---XXOXOOO-XOOXOOOXOXOXOO-OOOOOXXX---OOXX---O-XXX- X
---OO------OOO--OOOOOXOOOOOXOOOOXXXOOOOXXXXOXOX---OXOX---OOOOOO- X
-------X---O-XX-O-OOOXOO-OXOXOOOOXOOOXOOXXXOOOXO--OOOOOO--OOOXXO X
----OX-----OOX--XXOOXOXOOOOOOXXOOOOOOOXO-OOXXXOO--XXXX-O--XXXXX- X
--XXXXX-X--OOX--X-XOOOOOXXXOXOOOXXOOXOOO-XXOOOO---OOOO---OOO-X-- X
--XXX-----XOOO--XOOOOO--OOOOXO--OOOXOXX-OOXXXXX-OOOXXX--XXXXXXX- X
X-OXXXX--XOOOX--XXOOOOOOXXOXOOOOXXXXXOO-XXOOOOOX--OOO-----O----- X
--XOOX----OXOXXOXOXOOOXOOOOXOOXOOOXOOOXOOOOXOXOO----OO------OO-- X
-XXXXXX---XOOO--XXXXXXXO--OOXOX--OOOXXOX-XXOXOXX--XXXX-X--XXXX-- X
---X------OXX---OOOOXXXXXXOXOXXXOXOXOOX-OOXOOXX-OOOOOO--XOOOOO-- X
-OOOO---O-OOO---OOOOO---OOOOXOX-OOOXXOOOOOOOXXOOOOOXX--OO--XXO-- X
--OOOOO---OXOO-OOOOOOOOOOOOXXOXOOOOXOX--OXXXXX----XXOX----XXXX-- X
XXXXXX-OOOOOXX-OOOXXXXXOOOOXOXXOOOOXXOX-XXXXXXO----X-X---------- X
-XXXXX--X-XOX---XOXXXX-OXXXXXXO-XXXOXOOOXXXXOOO-X-OOOO---OOO---- X
-OOXX----OOOXX--XXOOOOX-XXXXXOXXXXXXXXOXXXXXXXXOX-OOOX----O----- X
-XXXXX----XOX---XXXXOO-XXXXXXOOO-XOXOXO-OOXXXOOOO--XOX---XXXXX-- X
---XX---OOXXXX--OOOOXXX-OOOOOOOOOOOXOOO-OOXXOO---XOOOO---XOOOO-- X
XXXXXX--OOOOXX--XOXXXO--XXOXXO--XXXOOOO-XXOOXO---OOXXO---OOOO--- X
--------O-XXXXXXOOOOOXXXOOOOXXXXOOXOXXOXO-XOOOXX--XOOO-----OOOO- X
--XXXXX---XXOX--OOOOXO--OOOXXOOOOOXOXO--OXOOXOO-O-OXXO---OOOOO-- X
OOOOOO--O-XXXO--OOOOXOOOOXXOXXOOOOXOXOO--OOXXOO--OXXXX----X----- X
-OOOOO--X-OOOO--XXXOOOOOXXOXXXOOXOXOOOXOXXOOOOOOX--O---O---O---- X
-XXXXX----XXXO--OXOXXOO-OXOXXOOOOOXXOXX-OOOOOXX---OOXX----OOOO-- X
--XXXX--X-XXXX--XXOOXXXXXOXOOXXX-OOXXXOX-OOOOOXX--OOOO----XO-O-- X
--OOOOO-XXOOOOO-XXXOOOOOXXOXOX--XXOOOOOOXXOXXXO---OOX-----O--X-- X
OXOOOO--OXXOOO--OXOOOOOOOXOOXOO-OOXXXXO-O-XXX-OO--XXX----OOO---- X
O-OOOO--XOOOOO--XXOOOOOOXXXXXOOOXXXOXOOO--XXOO----XXXO---OOO---- X
-OOOOOO-X-XOOO--XXXXXOXXXOXOOXO-XOXXXX-OXXOXX-----XOOO----OOOO-- X
--O-XXX---OOXX--OOOOXXXXOOOOXXXX-OOOXXXXXXXOXXXXX-XXOO------XO-- X
XOOOOOO-OOOOOO--OOXXOOO-XXOOXO--XXXOOOO-XXXOOO--XXXOO-----XO---- X
-----O----OOOO-X---OOOXX--OOOXOX-OOOXXOX-XOXXOXX--XOOO-X---OOOO- X % Wong Kevin - Ho Hotcolder (Hong-Kong Ladder)
----OOO-O--XOO---OXXO--OXOOXOO-O-OOXOXOOOOOOXOOO--XXXX----XX---- X % Ng Bunny - Ho Hotcolder (Hong-Kong Ladder)
---O------OOX----OXOXX--OOOOOOX-OXOOOOO-OOXXXXX-O-OXXX---OO-XXX- X % Stastna Jan - Vit Jiri (Parties tcheques)
-----------O----O-OOOOO-OOOOOOOOOOOOOOOXO-OOOOOX---OOOO---XOXXXX X % Pkmob (kanovsky) - Sic Vojtech (Parties tcheques)
--------X-O-----XXOO-O--XOXOOOO-XOXXXO--XOXXOOO-XXXOOO--XXXXXXX- O % Pkmob (kanovsky) - Kvapil Martin (Parties tcheques)
-OOOO-X-O-OOOX-OOOOOXOO-OXOXXOX-OOOOOOOX-OOOOO-O---O------------ X % Vit Jiri - Sic Vojtech (Parties tcheques)
---O-X--X-OOOO-X-XOOOOXXXXXOOOXXOXXOXXO--OXXX-OO--XXX-----X----- X % Pkmob (kanovsky) - Vit Jiri (Parties tcheques)
--OOOOO-X-OOXO---XOXOOO--OXXOO--OXOXXXXXXOOOXXX---OOX------O---- X % Pkmob (kanovsky) - Vit Jiri (Parties tcheques)
---OOO----OOOO--O-OOXOOOOXOXXOOOOXOOOXX-OOOOXX--O-OXX------X---- X % Vit Jiri - Voracek Miroslav (Parties tcheques)
-XXXXXXX--XXXOOOXOXXXX-OOOXXXXO-XXXOOO--XXOOOOO----------------- X % Pkmob (kanovsky) - Rybarik Jan (Parties tcheques)
--------O--XXO---OXXOXOO-OOOXOX-OOOOOXOXOOOOOOXXO--OOO-X----OO-- X % Kalfinov Zdravko - Pkmob (kanovsky) (Parties tcheques)
O--XXX--OOXX----OOXXXX--OOOXXXXXXXOOXXXXOXXOOO----XXOO---------- X % Pkmob (kanovsky) - Vit Jiri (Parties tcheques)
----------X-------X-XO-XOXXXXXXXOOXOOXOXOOOXXOXXOOOOXX----XXXXX- X % Hvezdova Jitka - Vit Jiri (Parties tcheques)
---XXX----XXXXO--XXOOOXXXXOOXXXXXXOXXXXXOOOXXX----XX-----X------ X % Rybarik Ivo - Vit Jiri (Parties tcheques)
-------------O--OX-XOOO--OXOXOX-OXOXOX--OXOOXX--XXOXXXX-OOOOOXXX X % Rybarik Ivo - Pkmob (kanovsky) (Parties tcheques)
-----X-----X-X--O---XXXXOO-OOXXXOXOOXXOXOOOOXOXX--XXXX-X--XXXX-- X % Rybarik Ivo - Vit Jiri (Parties tcheques)
------------O-----X-OOXO--XXOXOOOOXOOOOO-OOXOXX-XOXXXXXXO-OOOOO- X % Rybarik Jan - Vit Jiri (Parties tcheques)
-----X------XX--OOXXXXX-OOOOOX--OOOXXXX-OOOOXX--O-XOXX--OOOOOO-- X % Sic Vojtech - Pkmob (kanovsky) (Parties tcheques)
------OX------XO--X-XXOO---XXOOO--XXOOOO--XOOOOO--XXOOOOOOOOOOOO X % Kvapil Martin - Pkmob (kanovsky) (Parties tcheques)
--OOOOO---OOXO---XOXOOXXXXXXXXOOOOOOOOXO-OOOXXXX----X----------- X % Voracek Miroslav - Pkmob (kanovsky) (Parties tcheques)
--------O-XX----OOXXX---OOXXXXX-OOXOXOXXOOXXOXXX--XOXO---X-OOOO- X % Kvapil Martin - Vit Jiri (Parties tcheques)
------------X---XXXXXX--OOOOOOX-OOXOOXOOXXXXOXOO--OOXO---OOOOOO- X % Stastna Jan - Pkmob (kanovsky) (Parties tcheques)
-----------XX-----XXXXXXOOOXXXOX-OOOOXOX-XOXXXXX--OOOO-X-OOOOO-- X % Rybarik Ivo - Pkmob (kanovsky) (Parties tcheques)
----O-----OOO----OOOO----XOOOO---OXOOOOO-OOXOOO---OXXOOOXXXXXXXO X % Tastet Marc - Cottogni Gianni (International de Turin)
-XXXXX----XXOO--OOOXXOX--OOOXXO--OOOOOOOOOOOOOX----OO------OO--- X % Silvola Andrea - Cottogni Gianni (International de Turin)
-----------OO---OOOOOXXXXOXXXXXXXXOXXXXXXXOOXXXX--XOOX----X-O--- X % Cottogni Gianni - Ronca Antonello (International de Turin)
----------OOOO---OOOOOXX--OOOOXXOOOOOOXX-OOOOOXX---OOOOX---XXX-- X % Tucci Alessandro - Cottogni Gianni (International de Turin)
--OOOO--O-OOOO--OOOXXXOOOXOOXOOOOOXOOXOOO--OOOOO----O----------- X % Ferrando Marco - Cottogni Gianni (International de Turin)
--OOOOO-X-XOOO--XXXXOOX-XXXXXXXXXXOXOX--XXOOOOO-----OX---------- X % Bersaglieri Daniela - Cottogni Gianni (International de Turin)
--OX------XXXO--XXXXOXO-XOXOXOX-XXXOOOOOXXXOOO----XO-O----XOO--- X % Tucci Alessandro - Barnaba Donato (International de Turin)
---XXX----XXXX--OOXXXXX-OXXOXOOOOXXXXOO-O-XXOOO-O-X-OO-------O-- X % Ferrando Marco - Hubbard Geoff (International de Turin)
--OOOO--O-OOXX--OOOOOXO-OOOXOOO-OOXOXXOO-XXXXXOOX--X------------ X % Silvola Andrea - Stanzione Pierluigi (International de Turin)
--OOOO----XXOO---OXOOOXX-OOOOXXXOOOOXXOO-XOXXXO---OO-X----O----- X % Hubbard Geoff - Menozzi Giuseppe (International de Turin)
-XXXXX----XXXXOOXXXXXXO-XXXOOOXXXXXXOXO--XXOOO-O--X------------- X % Tucci Alessandro - Silvola Andrea (International de Turin)
-----------O----OOOOOOX--XXOOXX-XOXXOXX-XXXOXOX-X-OXXOO--OOOOOO- X % Tastet Marc - Ferrando Marco (International de Turin)
---OX-----OOXX-O-OOOOOO-XXXXXOXX-XXOOXXXO-XOOOX---OOOO-----OO--- X % Cordy Alexandre - Tastet Marc (International de Turin)
--OOO-----OOO----XXXOO-XXXXXOOO--XXXOOOO--XXOOOO---OXO----OOOOO- X % Cordy Alexandre - Hubbard Geoff (International de Turin)
----OX----OOOX-X-OOOOOXX-OOXOXXXOOOOXOXX-XXXOOX---XOOO------O--- X % Cordy Alexandre - Ferrando Marco (International de Turin)
----------XO-X---OXXXX-OOOXXXXO-OOXXXOOOOOOOOOO--XXOOO----XOOX-- X % Cordy Alexandre - Tastet Marc (International de Turin)
----------XOO---O-XOOO-XOOXXXOX-OOOXXXX-OOOOXXXX--OOOO---OOOOO-- X % Sperandio Roberto - Tastet Marc (International de Turin)
--XXXX-----XXX--XXXXXO---OOOXOOO-OOOXOO---OOOOXX--XOOO----OOOO-- X % Sperandio Roberto - Stanzione Pierluigi (International de Turin)
-OOOO---O-XOO---OOOXOO--OOXXXO--OOXXOXXX-XOXXXX-X-OXXX------X--- X % Sperandio Roberto - Kashiwabara Takuji (International de Turin)
--XO------XOOO---OOOOOX--OXOOXOXOXOOXOO-XXOXOXOO--OOXX----O-X--- X % Sperandio Roberto - Stanzione Pierluigi (International de Turin)
--OX------OOX---OOOXOXX-OOOXOOOOOOOXOOOOOOOOXX-X--OXXX------X--- X % Tastet Marc - Cordy Alexandre (International de Turin)
--OX------OOXX-O--OXXXO---OXXOO--OOXXXOOOOOXOOO---XXXO---X-OOOO- X % Tastet Marc - Barnaba Donato (International de Turin)
---O-X------O----OXXXXXX-XOXXOXXXXXOXXOXXXXOOOO---XXOO----XOOX-- X % Tastet Marc - Kashiwabara Takuji (International de Turin)
---XXX-----XXX-X--XXXXXX--XXXXXX---XXXXX---XXXXX--XXXXX-OOOOOO-- X % Cordy Alexandre - Menozzi Giuseppe (International de Turin)
--XXXXX-O-XOOX--OOXXOXX-OOOOOOXX--OOOXOX---OOOXX----OX-X----X--- X % Tucci Alessandro - Hubbard Geoff (International de Turin)
--OOOO----XOXO---XOXOXOOXOXOOXX-OOOXOXXX--OOOOXX----OO-X-----O-- X % Hubbard Geoff - Kashiwabara Takuji (International de Turin)
--OXXX----OOXX--XXOXXX---OOOXOX---OXOXOX-XOOXOOO--OOOO----XO-O-- X % Sperandio Roberto - Hubbard Geoff (International de Turin)
-OOOOO----OOOO--OOXXOOXOOXOOXXOOOXOOXOOOOOOOO---O----O---------- X % Kashiwabara Takuji - Bersaglieri Daniela (International de Turin)
--XX------XXX--X--XXXXXX--XXXXOX--XOXOOX--XXOOXX--XXXO-X--OOOOO- X % Cottogni Gianni - Menozzi Giuseppe (International de Turin)
--XXXXX---OOOO--XOOOOO--XXOOOOO-XXXXOOXX-XXXOXX----XX-------OX-- X % Kashiwabara Takuji - Cordy Alexandre (International de Turin)
XOOOOX---XOOXOO--XXXOOO--XXXOXOOXXXXXXO--XXXXXO------O------O--- X % Castellano Giorgio - Kashiwabara Takuji (International de Turin)
----------X-OX---XXOXX--XXOOOOOOOOOOOXX-OOOXXXO-OOOOXX----XXXX-- X % Castellano Giorgio - Cordy Alexandre (International de Turin)
--O--------OXX----OOOXOO--OOXOX-OOOXXXO-OXXXXOOOO-XXOX----XXXXX- X % Castellano Giorgio - Tastet Marc (International de Turin)
--OX-O----OOOO--XOOOOXX--XOOXO---XOXOXXXXXOOXOX---OXX-O---XXX--- X % Tastet Marc - Hubbard Geoff (International de Turin)
---XXX----XXXX----OXOX-O-OOOXXOO-OOOXOXO-XOOOXOO--OOOO-O--O-O--- X % Hubbard Geoff - Stanzione Pierluigi (International de Turin)
---OOXXO-OOOOXXX-XOXOOXX-XXOOXOX--XOOOOX--XXOO-X--XO-------O---- X % Menozzi Giuseppe - Ferrando Marco (International de Turin)
---OOO----OOOO---XXXXOX--OOOXOXX--OOXXX---OXOOX---XOOO-X-XXXX-O- X % Buccoliero Gianfran - Ferrando Marco (International de Turin)
---XXXX---XXOX----XXXX--OXXXXX--OOXOXXX-OOOXOXXX---OOO---XXX-O-- X % Ronca Antonello - Stanzione Pierluigi (International de Turin)
---X------XXO---XXOOOOXX-XOOOXOX-XXXOXXXXXXOOOXX--OOOO------OO-- X % Tastet Marc - Cordy Alexandre (International de Turin)
--XXXXX---XXOX-O--XOXOOO-XXXXOXO--XXXOOO--XXXOO---XXXO-----X-O-- X % Stanzione Pierluigi - Cordy Alexandre (International de Turin)
----XXX-----OOO----OOOOX-OOOXXOXOOOOXOOO---OXXOO--OOXX----XXXXX- X % Bersaglieri Daniela - Buccoliero Gianfran (International de Turin)
---O--------OO--X-XXXOXXXXOOOXOOXOXOXXOOOOOOOOO---XXXO----OOO--- X % Barnaba Donato - Hubbard Geoff (International de Turin)
---OO-X-X-OOOX--XXOOXOO-XOOOXXOOXOXXXXX---XXXX----XXXX-----X-O-- X % Stanzione Pierluigi - Tastet Marc (International de Turin)
----OX----OOOX---OOOOXX--XOOXXXX-XXOOXXO-XXOOXO---XOOO----XOOO-- X % Menozzi Giuseppe - Kashiwabara Takuji (International de Turin)
-----X------XX-----XXXOO--XXOXOO--XOOXXOOOOXOXOO-OXOXO-OO-OOOOO- X % Bersaglieri Daniela - Stanzione Pierluigi (International de Turin)
----OX----OOOX-X-XXXOXXX--XOOOXX--XOOXXX-XXOXXXX--XXXO----XX-O-- X % Bersaglieri Daniela - Menozzi Giuseppe (International de Turin)
----------XOO---XXOXOOOOOOOOXXXXOOXXOXX--OOXXOX---OOXX-----XXXX- X % Barnaba Donato - Menozzi Giuseppe (International de Turin)
---X-O----XXO---XXXXX---XXOXXX--XOXOXXX-XXOOOOO---OOOOX--OOOOO-- X % Buccoliero Gianfran - Cordy Alexandre (International de Turin)
---XXO----OXO-----OOXXXX--OXOXXX--OXXOXX--OXXOOX--XOXOO---XXXXX- X % Stanzione Pierluigi - Kashiwabara Takuji (International de Turin)
--XXXXX--XXXOO--OOXOOOX-OOOOXX--OOOOXX--OOOOXXX----OXX-----O---- X % Tucci Alessandro - Tastet Marc (International de Turin)
----------XX-O--OOXXOOX-OOOOXOO-OOXXXO--OOXXXO---XXOOX---XXXXXX- X % Silvola Andrea - Tastet Marc (International de Turin)
-----O-------O----OOXOX-XXXXXOX-XXXXOOXX-OOXOOO---XOOOOO-XXXXXX- X % Silvola Andrea - Cordy Alexandre (International de Turin)
---XXX-----OXXXO--OXXXX---OOXOXX--OOOXXXXXXXOXXX-XO-XO------XXO- X % Cottogni Gianni - Buccoliero Gianfran (International de Turin)
--XXXX--O-XOOOOXOOOOXOXXOOOXOXXXOOOOOXXX---OOOXX---------------- X % Castellano Giorgio - Buccoliero Gianfran (International de Turin)
--XXXO----OXOO-X--OXXOXX--OXXOOX-OOXXOOX---XXXXX--OXXX-X--OX---- X % Castellano Giorgio - Silvola Andrea (International de Turin)
-XXXX---O-XXXX--OOXXXXXXOXOXXXX-OOOOXXX-OOOOOO----XOO----------- X % Castellano Giorgio - Tucci Alessandro (International de Turin)
----OOO-O-OOOX--OXOXXO--OXOXXXXXOOXOXO--O-OOOO----XOOO----XXX--- X % Hubbard Geoff - Buccoliero Gianfran (International de Turin)
--OOOOXO--OOOOOO--OOXXXX--OXOOX-XOXOOOO-XXOOOO--X-X-O-----X----- X % Tucci Alessandro - Sperandio Roberto (International de Turin)
-----X----OXXX-O--OOXXOO-OOOOOOO-XXXOOOO-XXXXOOO--XXOX------XXX- X % Buccoliero Gianfran - Silvola Andrea (International de Turin)
---XXXX---XXXX---XXXXOOXX-XXXOOO-XXOXOO--OOOOOOO---OOX-----OX--- X % Cordy Alexandre - Sperandio Roberto (International de Turin)
----X---O-O-XX--OOOOXXX-OOOXOXXXOOXOXOO-OOXXOOO---XXOO------XO-- X % Bersaglieri Daniela - Tucci Alessandro (International de Turin)
--OOOOO---OOOX-O-XXXOOOO--XXXOOO--XXXOOO--XXOOOO---OOOX---O----- X % Sperandio Roberto - Castellano Giorgio (International de Turin)
---X-O------OO-X--OOOOXX--OOOXXX--OOXXOXOOOOOXXX--XXXO-X--XXX-O- X % Stanzione Pierluigi - Castellano Giorgio (International de Turin)
----------XXXO-O--OXOOOO--OOOOOO--OOOXXOOOOOXXO---XOOX-X--XXXXX- X % Silvola Andrea - Sperandio Roberto (International de Turin)
----O------OO--O-XO-OXOO-XOOOOOOXXOXOXXOXXOOXXX---OXXX-X--XX-O-- X % Stanzione Pierluigi - Sperandio Roberto (International de Turin)
-OOOO-----OXOX--XXXXXXXO-XOXXXO--XXOXOO---XXOO-----OXO----OOOOO- X % Tucci Alessandro - Buccoliero Gianfran (International de Turin)
--------X-OOO---XXOOOO--XXXOOXX-XXXXOXXXXXOOOOX-X-XXOO----X-OO-- X % Cottogni Gianni - Castellano Giorgio (International de Turin)
-X-OOO---XOOOO---OOOOOOOXOOXXX--OXXXXXX---XOXX----XXX----XXXX--- X % Ronca Antonello - Castellano Giorgio (International de Turin)
--OOXX----XXOX-X--XXOOXX--OOXXOX--OOXXOX--OOOXXX---OOO-----OOOO- X % Menozzi Giuseppe - Buccoliero Gianfran (International de Turin)
----O--------O-O-OOOOXOO-OOOOXXO-OOOXOOO-OOXOXOO--OOXO-O--OOOO-- X % Ferrando Marco - Ronca Antonello (International de Turin)
-O--XXX---O-OO---X-OOOOO--XOOOXOXXXOOXXO--XOXOOO---OOO-O---OOO-- X % Menozzi Giuseppe - Tucci Alessandro (International de Turin)
-XXX--X---OOXX---OOXXOOO-OOXOOOO-XOOOXOO--OOOOX---OXXO-X----X--- X % Menozzi Giuseppe - Castellano Giorgio (International de Turin)
---OOO----OOOX----OOXXOO-OOOXXO---OXOOXO-OOOOXOO--XXXX-O---XXX-- X % Ferrando Marco - Sperandio Roberto (International de Turin)
-----O----OOOO--O-OOXXXXXOXXXXXX-XOXOOOX--OOXOXX--OXXX-X---XX--- X % Hubbard Geoff - Silvola Andrea (International de Turin)
---X------X-XX----OXOXO-XOOOXOOOXOOXOXOOXOOOOOOOX-OOOX-----OX--- X % Menozzi Giuseppe - Silvola Andrea (International de Turin)
----X-------X-----XXXOO-XXXOXOOXOXOOXOOX-OOXXXXX-OOXXX-X--XOOX-- X % Stanzione Pierluigi - Sperandio Roberto (International de Turin)
-----XXX-----XXX---OXXXX---XOOXX--XOXXOX-XXXXXXX--XOXXOX--XXXXX- O % Kashiwabara Takuji - Cottogni Gianni (International de Turin)
